# Min Max Scaler

In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
x = np.array([[1, 2,  3], [4,  5, 6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
minmax.fit(x).transform(x)

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [4]:
#Para primera columna
x_std_0 = (1-1)/(7-1)
print(x_std_0)
x_std_4 = (4-1)/(7-1) 
print(x_std_4)
x_std_7 = (7-1)/(7-1) 
print(x_std_7)

0.0
0.5
1.0


# Scaler

In [5]:
standar = preprocessing.StandardScaler().fit(x)
standar.transform(x) 

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [6]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#np.std(x[:,0]) = np.std([1,4,7]) = desviación standard
x_std_0 = (1-4)/np.std(x[:,0])
print(x_std_0)
x_std_4 = (4-4)/np.std(x[:,0])
print(x_std_4)
x_std_7 = (7-4)/np.std(x[:,0])
print(x_std_7)

-1.2247448713915892
0.0
1.2247448713915892


In [8]:
np.std(x[:,0])

2.449489742783178

In [9]:
x2 = np.array([[1, 2,  3], [4,  5, 6], [7, 8, 9]])
x2
standar = preprocessing.StandardScaler().fit(x2)
standar.transform(x2) 

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

# Binarización

In [10]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
datosb = preprocessing.Binarizer(threshold=6).transform(x)
datosb

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

# Normalización

In [12]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
datos_n = preprocessing.normalize(x, norm='l1', axis=0)
datos_n

array([[0.08333333, 0.13333333, 0.16666667],
       [0.33333333, 0.33333333, 0.33333333],
       [0.58333333, 0.53333333, 0.5       ]])